spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rbacdb
    username: postgres
    password: yourpassword
    driver-class-name: org.postgresql.Driver

  mybatis:
    type-aliases-package: com.aitech.rbac.model
    configuration:
      map-underscore-to-camel-case: true

server:
  port: 8080
