spring:
  datasource:
    url: jdbc:h2:mem:rbacdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  mybatis:
    type-aliases-package: com.aitech.rbac.model
    configuration:
      map-underscore-to-camel-case: true

server:
  port: 8080

security:
  jwt:
    secret-key: ${JWT_SECRET:change-me}
    expiration: 3600000
